#ifndef ARROW_BUILDER_H
#define ARROW_BUILDER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef ARROW_READER_H
#include "arrow_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#ifndef FILE_BUILDER_H
#include "File_builder.h"
#endif
#ifndef MESSAGE_BUILDER_H
#include "Message_builder.h"
#endif
#ifndef SPARSETENSOR_BUILDER_H
#include "SparseTensor_builder.h"
#endif
#ifndef TENSOR_BUILDER_H
#include "Tensor_builder.h"
#endif
#ifndef SCHEMA_BUILDER_H
#include "Schema_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#include "flatcc/flatcc_epilogue.h"
#endif /* ARROW_BUILDER_H */
