#ifndef ARROW_VERIFIER_H
#define ARROW_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef ARROW_READER_H
#include "arrow_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#ifndef FILE_VERIFIER_H
#include "File_verifier.h"
#endif
#ifndef MESSAGE_VERIFIER_H
#include "Message_verifier.h"
#endif
#ifndef SPARSETENSOR_VERIFIER_H
#include "SparseTensor_verifier.h"
#endif
#ifndef TENSOR_VERIFIER_H
#include "Tensor_verifier.h"
#endif
#ifndef SCHEMA_VERIFIER_H
#include "Schema_verifier.h"
#endif
#include "flatcc/flatcc_prologue.h"


#include "flatcc/flatcc_epilogue.h"
#endif /* ARROW_VERIFIER_H */
