#ifndef SIMPLE_READER_H
#define SIMPLE_READER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "NOOB"
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct Eclectic_FooBar_table *Eclectic_FooBar_table_t;
typedef struct Eclectic_FooBar_table *Eclectic_FooBar_mutable_table_t;
typedef const flatbuffers_uoffset_t *Eclectic_FooBar_vec_t;
typedef flatbuffers_uoffset_t *Eclectic_FooBar_mutable_vec_t;
#ifndef Eclectic_FooBar_file_identifier
#define Eclectic_FooBar_file_identifier "NOOB"
#endif
/* deprecated, use Eclectic_FooBar_file_identifier */
#ifndef Eclectic_FooBar_identifier
#define Eclectic_FooBar_identifier "NOOB"
#endif
#define Eclectic_FooBar_type_hash ((flatbuffers_thash_t)0xa604f58)
#define Eclectic_FooBar_type_identifier "\x58\x4f\x60\x0a"
#ifndef Eclectic_FooBar_file_extension
#define Eclectic_FooBar_file_extension "bin"
#endif

typedef int8_t Eclectic_Fruit_enum_t;
__flatbuffers_define_integer_type(Eclectic_Fruit, Eclectic_Fruit_enum_t, 8)
#define Eclectic_Fruit_Banana ((Eclectic_Fruit_enum_t)INT8_C(-1))
#define Eclectic_Fruit_Orange ((Eclectic_Fruit_enum_t)INT8_C(42))

static inline const char *Eclectic_Fruit_name(Eclectic_Fruit_enum_t value)
{
    switch (value) {
    case Eclectic_Fruit_Banana: return "Banana";
    case Eclectic_Fruit_Orange: return "Orange";
    default: return "";
    }
}

static inline int Eclectic_Fruit_is_known_value(Eclectic_Fruit_enum_t value)
{
    switch (value) {
    case Eclectic_Fruit_Banana: return 1;
    case Eclectic_Fruit_Orange: return 1;
    default: return 0;
    }
}



struct Eclectic_FooBar_table { uint8_t unused__; };

static inline size_t Eclectic_FooBar_vec_len(Eclectic_FooBar_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Eclectic_FooBar_table_t Eclectic_FooBar_vec_at(Eclectic_FooBar_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Eclectic_FooBar_table_t, vec, i, 0)
__flatbuffers_table_as_root(Eclectic_FooBar)

__flatbuffers_define_scalar_field(0, Eclectic_FooBar, meal, Eclectic_Fruit, Eclectic_Fruit_enum_t, INT8_C(-1))
/* Skipping deprecated field: 'Eclectic_FooBar_density' */

__flatbuffers_define_string_field(2, Eclectic_FooBar, say, 0)
__flatbuffers_define_scalar_field(3, Eclectic_FooBar, height, flatbuffers_int16, int16_t, INT16_C(0))


#include "flatcc/flatcc_epilogue.h"
#endif /* SIMPLE_READER_H */
