#ifndef SIMPLE_VERIFIER_H
#define SIMPLE_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef SIMPLE_READER_H
#include "simple_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int Eclectic_FooBar_verify_table(flatcc_table_verifier_descriptor_t *td);

static int Eclectic_FooBar_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* meal */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* say */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* height */)) return ret;
    return flatcc_verify_ok;
}

static inline int Eclectic_FooBar_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Eclectic_FooBar_identifier, &Eclectic_FooBar_verify_table);
}

static inline int Eclectic_FooBar_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Eclectic_FooBar_type_identifier, &Eclectic_FooBar_verify_table);
}

static inline int Eclectic_FooBar_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Eclectic_FooBar_verify_table);
}

static inline int Eclectic_FooBar_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Eclectic_FooBar_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SIMPLE_VERIFIER_H */
