#ifndef SIMPLE_BUILDER_H
#define SIMPLE_BUILDER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef SIMPLE_READER_H
#include "simple_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "NOOB"
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __Eclectic_Fruit_formal_args , Eclectic_Fruit_enum_t v0
#define __Eclectic_Fruit_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, Eclectic_Fruit, Eclectic_Fruit_enum_t)

static const flatbuffers_voffset_t __Eclectic_FooBar_required[] = { 0 };
typedef flatbuffers_ref_t Eclectic_FooBar_ref_t;
static Eclectic_FooBar_ref_t Eclectic_FooBar_clone(flatbuffers_builder_t *B, Eclectic_FooBar_table_t t);
__flatbuffers_build_table(flatbuffers_, Eclectic_FooBar, 4)

#define __Eclectic_FooBar_formal_args , Eclectic_Fruit_enum_t v0, flatbuffers_string_ref_t v2, int16_t v3
#define __Eclectic_FooBar_call_args , v0, v2, v3
static inline Eclectic_FooBar_ref_t Eclectic_FooBar_create(flatbuffers_builder_t *B __Eclectic_FooBar_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Eclectic_FooBar, Eclectic_FooBar_file_identifier, Eclectic_FooBar_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, Eclectic_FooBar_meal, Eclectic_Fruit, Eclectic_Fruit_enum_t, 1, 1, INT8_C(-1), Eclectic_FooBar)
/* Skipping build of deprecated field: 'Eclectic_FooBar_density' */

__flatbuffers_build_string_field(2, flatbuffers_, Eclectic_FooBar_say, Eclectic_FooBar)
__flatbuffers_build_scalar_field(3, flatbuffers_, Eclectic_FooBar_height, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), Eclectic_FooBar)

static inline Eclectic_FooBar_ref_t Eclectic_FooBar_create(flatbuffers_builder_t *B __Eclectic_FooBar_formal_args)
{
    if (Eclectic_FooBar_start(B)
        || Eclectic_FooBar_say_add(B, v2)
        || Eclectic_FooBar_height_add(B, v3)
        || Eclectic_FooBar_meal_add(B, v0)) {
        return 0;
    }
    return Eclectic_FooBar_end(B);
}

static Eclectic_FooBar_ref_t Eclectic_FooBar_clone(flatbuffers_builder_t *B, Eclectic_FooBar_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Eclectic_FooBar_start(B)
        || Eclectic_FooBar_say_pick(B, t)
        || Eclectic_FooBar_height_pick(B, t)
        || Eclectic_FooBar_meal_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Eclectic_FooBar_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SIMPLE_BUILDER_H */
